version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.19
    working_directory: ~/go/src/github.com/screwyprof/payment
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: ./tools/coverage.sh
      - run: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN